name: Create an AKS cluster
description: Create an AKS cluster
inputs:
  cluster_name:
    description: ''
    required: true
  location:
    description: ''
    required: true
  version:
    description: ''
    required: false
    default: ''
  node_count:
    description: ''
    required: false
    default: 2
  tags:
    description: ''
    required: false
    default: ''
  taints:
    description: ''
    required: false
    default: ''
runs:
  using: composite
  steps:
    - name: Get runner public IP
      id: get-runner-ip
      uses: ./.github/actions/get-runner-ip
      with:
        source: https://whatismyip.azurewebsites.net/json/
        parsing: json
        json-key: ip

    - name: Create AKS cluster
      shell: bash
      run: |
        TAGS=""
        VERSION=""

        if [[ -n "${INPUTS_TAGS}" ]]; then
          TAGS="--tags ${INPUTS_TAGS}"
        fi

        if [[ -n "${INPUTS_VERSION}" ]]; then
          VERSION="--kubernetes-version ${INPUTS_VERSION}"
        fi

        # Create group
        az group create \
          --name ${INPUTS_CLUSTER_NAME} \
          --location ${INPUTS_LOCATION} \
          $TAGS

        # Create AKS cluster
        az aks create \
          --resource-group ${INPUTS_CLUSTER_NAME} \
          --name ${INPUTS_CLUSTER_NAME} \
          --location ${INPUTS_LOCATION} \
          $VERSION \
          --network-plugin none \
          --node-count "$(( ${INPUTS_NODE_COUNT} + 2 ))" \
          --ip-families ipv4,ipv6 \
          ${INPUTS_TAINTS} \
          --generate-ssh-keys \
          --api-server-authorized-ip-ranges ${{ steps.get-runner-ip.outputs.cidr }}
      env:
        INPUTS_TAGS: ${{ inputs.tags }}
        INPUTS_VERSION: ${{ inputs.version }}
        INPUTS_CLUSTER_NAME: ${{ inputs.cluster_name }}
        INPUTS_LOCATION: ${{ inputs.location }}
        INPUTS_NODE_COUNT: ${{ inputs.node_count }}
        INPUTS_TAINTS: ${{ inputs.taints }}

    - name: Get cluster credentials
      shell: bash
      run: |
        az aks get-credentials \
          --resource-group ${INPUTS_CLUSTER_NAME} \
          --name ${INPUTS_CLUSTER_NAME}
      env:
        INPUTS_CLUSTER_NAME: ${{ inputs.cluster_name }}

    - name: Patch nodes without Cilium
      uses: ./.github/actions/nodes-without-cilium
