name: Add external targets to kind cluster
description: |
  Add additional containers to the kind network which can be
  used as external targets for cilium-cli connectivity tests.
inputs:
  kind_network:
    description: "Name of the docker network created for kind"
    required: true
  ipv4_external_target:
    description: "IPv4 address of the first external target"
    required: true
  ipv4_other_external_target:
    description: "IPv4 address of the second external target"
    required: true
  ipv6_external_target:
    description: "IPv6 address of the first external target"
    required: true
  ipv6_other_external_target:
    description: "IPv6 address of the second external target"
    required: true
  lvh:
    required: false
    description: "Whether to SSH into LVH"
    default: 'false'
outputs:
  external_target_name:
    description: "Domain name of the first external target"
    value: ${{ steps.add_targets.outputs.external_target_name }}
  other_external_target_name:
    description: "Domain name of the second external target"
    value: ${{ steps.add_targets.outputs.other_external_target_name }}
runs:
  using: composite
  steps:
    - id: add_targets
      shell: bash
      run: |
        bash ./.github/actions/kind-external-targets/action.sh \
          ${INPUTS_LVH} \
          ${INPUTS_KIND_NETWORK} \
          ${INPUTS_IPV4_EXTERNAL_TARGET} \
          ${INPUTS_IPV4_OTHER_EXTERNAL_TARGET} \
          ${INPUTS_IPV6_EXTERNAL_TARGET} \
          ${INPUTS_IPV6_OTHER_EXTERNAL_TARGET}
      env:
        INPUTS_LVH: ${{ inputs.lvh }}
        INPUTS_KIND_NETWORK: ${{ inputs.kind_network }}
        INPUTS_IPV4_EXTERNAL_TARGET: ${{ inputs.ipv4_external_target }}
        INPUTS_IPV4_OTHER_EXTERNAL_TARGET: ${{ inputs.ipv4_other_external_target }}
        INPUTS_IPV6_EXTERNAL_TARGET: ${{ inputs.ipv6_external_target }}
        INPUTS_IPV6_OTHER_EXTERNAL_TARGET: ${{ inputs.ipv6_other_external_target }}
